export const NEWS_DATA = [
  {
    id: '01',
    to: '/content/',
    label: 'audio',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/c6DYFGt/news-1.png',
  },
  {
    id: '02',
    to: '/content/',
    label: 'video',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/Vt1W30D/news-2.png',
  },
  {
    id: '03',
    to: '/content/',
    label: 'article',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/BL1hpqc/news-3.png',
  },
  {
    id: '04',
    to: '/content/',
    label: 'audio',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/c6DYFGt/news-1.png',
  },
  {
    id: '05',
    to: '/content/',
    label: 'video',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/Vt1W30D/news-2.png',
  },
  {
    id: '06',
    to: '/content/',
    label: 'article',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/BL1hpqc/news-3.png',
  },
  {
    id: '07',
    to: '/content/',
    label: 'video',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/DtSLt8f/news-5.png',
  },
  {
    id: '08',
    to: '/content/',
    label: 'article',
    title: 'Commonwealth Genesis, A Love Story',
    date: '18/03/21',
    author: 'Erich Wasserman',
    url: 'https://i.ibb.co/q77qLFb/news-4.png',
  },
]
